export const ART_STYLES = [
  "Styles",
  "Default",
  "Indigenous",
  "Coloring Book",
  "Anime",
  "Cyberpunk",
  "Isometric",
  "Chibi",
  "Nebula",
  "Mythology",
  "Oil Painting",
  "Watercolor",
  "Pencil Sketch",
  "Double Exposure"
  "Charcoal",
  "Ink Drawing",
  "Low Poly",
  "Voxel",
  "Pixel Art",
  "3D Render",
  "Photorealistic",
  "Studio Lighting",
  "Cinematic",
  "Concept Art",
  "Fantasy",
  "Dark Fantasy",
  "Sci-Fi",
  "Steampunk",
  "Dieselpunk",
  "Biopunk",
  "Retro Futurism",
  "Synthwave",
  "Vaporwave",
  "Glitch Art",
  "Surrealism",
  "Abstract",
  "Minimalist",
  "Pop Art",
  "Comic Book",
  "Manga",
  "Ukiyo-e",
  "Impressionist",
  "Expressionist",
  "Cubist",
  "Art Nouveau",
  "Art Deco",
  "Baroque",
  "Renaissance",
  "Gothic",
  "Romanticism",
  "Symbolism",
  "Brutalism",
  "Fauvism",
  "Suprematism",
  "Constructivism",
  "Graffiti",
  "Street Art",
  "Tattoo Style",
  "Line Art",
  "Silhouette",
  "Neon Glow",
  "Holographic",
  "Glassmorphism",
  "Claymation",
  "Stop Motion",
  "Paper Cut",
  "Origami",
  "Woodcut",
  "Etching",
  "Blueprint",
  "Architectural",
  "Interior Design",
  "Product Shot",
  "Fashion Editorial",
  "Macro Photography",
  "Astrophotography",
  "Underwater",
  "Aerial View",
  "Tilt-Shift",
  "HDR",
  "Long Exposure",
  "Infrared",
  "Night Vision",
  "Thermal",
  "X-Ray Style",
];
