"use client";

import * as React from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Download, Share2 } from "lucide-react";

export interface ImageDisplayProps {
  image: string | null | undefined;
  provider: string;
  showProvider?: boolean;
  modelId?: string;
  timing?: import("@/lib/image-types").ProviderTiming;
  failed?: boolean;
  enabled?: boolean;
}

export function ImageDisplay({
  image,
  provider,
  showProvider = false,
  modelId,
  timing,
  failed = false,
  enabled = true,
}: ImageDisplayProps) {
  // Handler to download the image. If no image is available this is a no-op.
  const downloadImage = React.useCallback(() => {
    if (!image) return;
    const a = document.createElement("a");
    a.href = image;
    a.download = modelId ? `aiexor-${modelId}.png` : "aiexor-image.png";
    a.click();
  }, [image, modelId]);

  // Handler to share the image via the Web Share API. Falls back to an
  // alert when sharing is not supported or when no image is available.
  const shareImage = React.useCallback(async () => {
    if (!image) return;
    if (navigator.share) {
      await navigator.share({
        title: "Aiexor Image",
        text: `Created with Aiexor (${provider}${modelId ? ` - ${modelId}` : ""})`,
        url: image,
      });
    } else {
      alert("Sharing not supported on this device.");
    }
  }, [image, provider, modelId]);

  let content: React.ReactNode;
  if (failed) {
    content = (
      <div className="flex items-center justify-center w-full h-64 bg-red-50 text-red-500">
        Failed to generate image
      </div>
    );
  } else if (!image) {
    content = (
      <div className="flex items-center justify-center w-full h-64 bg-neutral-900 text-neutral-400">
        {timing?.elapsed !== undefined ? (
          <span>Generating… {(timing.elapsed / 1000).toFixed(1)}s</span>
        ) : (
          <span>Waiting for image…</span>
        )}
      </div>
    );
  } else {
    content = (
      <Image
        src={image}
        alt={modelId ? `Generated by ${modelId}` : "Generated"}
        width={600}
        height={400}
        className="w-full h-auto object-cover"
      />
    );
  }

  return (
    <div
      className={
        "relative rounded-xl overflow-hidden border border-[hsl(var(--glow))] shadow-[0_0_10px_hsl(var(--glow)/0.5)] bg-black" +
        (enabled ? "" : " opacity-50")
      }
    >
      {content}
      {image && !failed && (
        <div className="absolute bottom-2 left-2 flex gap-2">
          <Button
            size="icon"
            onClick={downloadImage}
            className="bg-black/70 text-white border border-[hsl(var(--glow))] rounded-full hover:shadow-[0_0_10px_hsl(var(--glow))]"
          >
            <Download className="w-4 h-4" />
          </Button>
          <Button
            size="icon"
            onClick={shareImage}
            className="bg-black/70 text-white border border-[hsl(var(--glow))] rounded-full hover:shadow-[0_0_10px_hsl(var(--glow))]"
          >
            <Share2 className="w-4 h-4" />
          </Button>
        </div>
      )}
      {showProvider && (
        <div className="absolute top-2 right-2 text-xs text-[hsl(var(--glow))] bg-black/70 px-2 py-1 rounded-md">
          {provider}
          {modelId && <span className="opacity-70 ml-1">({modelId})</span>}
        </div>
      )}
    </div>
  );
}
