// lib/artStyles.ts
export const ART_STYLES: string[] = [
  "Photorealistic",
  "Ultra Realistic",
  "Cinematic",
  "HDR",
  "Studio Lighting",
  "Portrait Photography",
  "Macro Photography",
  "Long Exposure",
  "Bokeh",
  "Film Grain",
  "Analog Photo",
  "Polaroid",
  "Infrared",
  "Night Photography",
  "Digital Art",
  "Concept Art",
  "Matte Painting",
  "Environment Art",
  "Character Design",
  "Game Art",
  "Splash Art",
  "Key Art",
  "Illustration",
  "Anime",
  "Manga",
  "Chibi",
  "Studio Ghibli Style",
  "Kawaii",
  "Mecha",
  "Cyberpunk Anime",
  "Dark Anime",
  "Isekai Style",
  "Cyberpunk",
  "Steampunk",
  "Dieselpunk",
  "Biopunk",
  "Retrofuturism",
  "Futuristic Sci-Fi",
  "Space Art",
  "Galaxy Scene",
  "Nebula",
  "Alien World",
  "Fantasy",
  "Dark Fantasy",
  "High Fantasy",
  "Epic Fantasy",
  "Mythology",
  "Medieval Fantasy",
  "Dungeons and Dragons",
  "Magic Realism",
  "Oil Painting",
  "Watercolor",
  "Acrylic Painting",
  "Ink Drawing",
  "Charcoal Sketch",
  "Pencil Drawing",
  "Pastel Drawing",
  "Ink Wash",
  "Impressionism",
  "Expressionism",
  "Abstract",
  "Abstract Expressionism",
  "Surrealism",
  "Cubism",
  "Pop Art",
  "Minimalism",
  "Modern Art",
  "Art Nouveau",
  "Art Deco",
  "Baroque",
  "Renaissance",
  "Ukiyo-e",
  "Pixel Art",
  "8-bit",
  "16-bit",
  "Retro Game Art",
  "Isometric",
  "Low Poly",
  "Voxel Art",
  "Wireframe",
  "Blueprint",
  "3D Render",
  "Hyperreal 3D",
  "Octane Render",
  "Unreal Engine",
  "Blender Render",
  "ZBrush Sculpt",
  "Clay Render",
  "Graffiti",
  "Street Art",
  "Tattoo Flash",
  "Album Cover",
  "Poster Design",
  "Editorial Illustration",
  "Comic Book",
  "Graphic Novel",
  "Line Art",
  "Flat Design"
];
