const artStyles = [
  "Photorealistic",
  "Ultra Realism",
  "Hyperrealism",
  "Cinematic",
  "Studio Lighting",
  "HDR",
  "Film Grain",
  "Long Exposure",
  "Macro Photography",
  "Portrait Photography",
  "Landscape Photography",
  "Nature Photography",
  "Astrophotography",
  "Oil Painting",
  "Watercolor",
  "Acrylic Painting",
  "Gouache",
  "Ink Wash",
  "Charcoal Sketch",
  "Pencil Drawing",
  "Line Art",
  "Minimalist Line Art",
  "Anime",
  "Manga",
  "Comic Book",
  "Graphic Novel",
  "Pixel Art",
  "8-bit",
  "16-bit",
  "Voxel Art",
  "Low Poly",
  "3D Render",
  "Isometric",
  "Claymation",
  "Stop Motion",
  "Digital Painting",
  "Concept Art",
  "Matte Painting",
  "Fantasy Illustration",
  "Dark Fantasy",
  "Sci-Fi",
  "Cyberpunk",
  "Steampunk",
  "Dieselpunk",
  "Biopunk",
  "Retrofuturism",
  "Vaporwave",
  "Synthwave",
  "Glitch Art",
  "Surrealism",
  "Abstract",
  "Abstract Expressionism",
  "Cubism",
  "Pop Art",
  "Art Deco",
  "Art Nouveau",
  "Baroque",
  "Renaissance",
  "Ukiyo-e",
  "Japanese Ink",
  "Chinese Ink",
  "Calligraphy Style",
  "Stencil Art",
  "Graffiti",
  "Street Art",
  "Neon Glow",
  "Infrared",
  "Holographic",
  "AR/VR Render",
  "Blueprint",
  "Wireframe",
  "Architectural Visualization",
  "Product Render",
  "Fashion Editorial",
  "Album Cover",
  "Poster Design",
  "Logo Design",
  "Tattoo Design",
  "Vector Art",
  "Flat Design",
  "Fractal Art",
  "Generative Art",
  "AI Abstract",
  "Dreamlike",
  "Ethereal",
  "Mythological",
  "Space Art",
  "Galaxy Scene",
  "Starfield",
  "Cosmic Horror",
  "Noir",
  "High Contrast",
  "Moody Lighting"
];

export default artStyles;
