const artStyles = [
  "Photorealistic",
  "Ultra Realistic",
  "Cinematic",
  "Cinematic Lighting",
  "Hyperrealism",
  "Studio Portrait",
  "Film Still",
  "HDR Photography",
  "Macro Photography",
  "Long Exposure",

  "Digital Art",
  "Concept Art",
  "Matte Painting",
  "Environment Design",
  "Character Design",
  "Key Art",
  "Splash Art",

  "Oil Painting",
  "Watercolor",
  "Acrylic Painting",
  "Ink Illustration",
  "Charcoal Sketch",
  "Pencil Drawing",
  "Pastel Drawing",
  "Etching",

  "Anime",
  "Manga",
  "Studio Ghibli",
  "Shonen Anime",
  "Seinen Anime",
  "Chibi",
  "Anime Portrait",

  "Pixel Art",
  "Voxel Art",
  "Low Poly",
  "Isometric",
  "Retro Game Art",
  "8-bit",
  "16-bit",

  "Cyberpunk",
  "Steampunk",
  "Dieselpunk",
  "Biopunk",
  "Solarpunk",
  "Futuristic Sci-Fi",
  "Space Opera",

  "Fantasy Illustration",
  "Dark Fantasy",
  "High Fantasy",
  "Mythological",
  "Epic Fantasy",
  "Dungeons & Dragons",

  "Surrealism",
  "Abstract",
  "Minimalism",
  "Expressionism",
  "Impressionism",
  "Cubism",
  "Pop Art",

  "Neon Glow",
  "Holographic",
  "Synthwave",
  "Vaporwave",
  "Retrofuturism",

  "Line Art",
  "Monochrome",
  "Black & White",
  "Silhouette",
  "Blueprint",

  "3D Render",
  "Octane Render",
  "Unreal Engine",
  "Blender Render",
  "Clay Render",

  "Product Photography",
  "Fashion Editorial",
  "Street Photography",
  "Architectural Visualization",
  "Interior Design Render",

  "Tattoo Design",
  "Graffiti",
  "Comic Book",
  "Graphic Novel",
  "Poster Art",
]

export default artStyles
